// Generated by CoffeeScript 1.6.3
(function() {
  var acts_as_dumb_link, acts_as_link, campaigning_done, hover_border_link, is_platform_page, show_cta, smooth_scroll;

  hover_border_link = function($link_el, $border_el, base_c, hover_c) {
    return $link_el.hover(function(_) {
      return $border_el.css({
        'border-color': hover_c
      });
    }, function(_) {
      return $border_el.css({
        'border-color': base_c
      });
    });
  };

  acts_as_dumb_link = function($el) {
    return $el.click(function() {
      return $(this).find('a:first').click();
    });
  };

  acts_as_link = function($el) {
    return $el.click(function() {
      var $a, url;
      $a = $(this).find('a:first');
      url = $a.attr('href');
      if ($a.attr('target') === '_blank') {
        return window.open(url, '_blank');
      } else {
        return window.location.href = url;
      }
    });
  };

  smooth_scroll = function(offset) {
    if (offset == null) {
      offset = 0;
    }
    return $("a[href*=#]:not([href=#])").click(function() {
      var target;
      if (location.pathname.replace(/^\//, '') === this.pathname.replace(/^\//, '') && location.hostname === this.hostname) {
        target = $(this.hash);
        if (!target.length) {
          target = $("[name=" + (this.hash.slice(1)) + "]");
        }
        if (target.length) {
          $('html, body').animate({
            scrollTop: target.offset().top + offset
          }, 1000);
          return false;
        }
      }
    });
  };

  campaigning_done = function() {
    return new Date() > new Date('02/10/2014 23:00');
  };

  is_platform_page = function() {
    return window.location.href.indexOf('platform') > -1;
  };

  show_cta = function($cta) {
    $cta.show();
    return $('body').addClass('vote-now');
  };

  $(function() {
    var $endorsement_collection, $target, active_class;
    $(document).foundation({
      section: {
        multi_expand: true
      }
    });
    $('.accordion-no-expand').foundation({
      section: {
        multi_expand: false
      }
    });
    hover_border_link($('.blog-cta'), $('#blog-border'), $('#blog-border').css('border-color'), '#222');
    acts_as_link($('.acts-as-link'));
    $('#to-top').click(function(e) {
      e.preventDefault();
      return $('body').animate({
        scrollTop: 0
      });
    });
    if (campaigning_done()) {
      show_cta($('#vote-cta'));
      acts_as_dumb_link($('#vote-cta'));
      if (!sessionStorage.hidemodal) {
        sessionStorage.hidemodal = true;
        $('#voteModal').foundation('reveal', 'open');
      }
    }
    $endorsement_collection = $('#endorsement-collection');
    $endorsement_collection.imagesLoaded(function() {
      return $endorsement_collection.isotope({
        itemSelector: '.endorsement',
        filter: '*',
        masonry: {
          columnWidth: 495
        }
      });
    });
    $('#endorsement-filters a').click(function(e) {
      var $parent, selector;
      e.preventDefault();
      $parent = $(this).parent();
      selector = $(this).data('filter');
      $endorsement_collection.isotope({
        filter: selector
      });
      $parent.siblings().removeClass('active');
      return $parent.addClass('active');
    });
    $('#platform-filters a').click(function(e) {
      var $parent, $siblings, selector, sibling_selectors;
      $parent = $(this).parent();
      selector = $(this).data('filter');
      $siblings = $parent.siblings();
      sibling_selectors = $siblings.find('a').data('filter');
      $(sibling_selectors).fadeOut(200, function() {
        return $(selector).fadeIn(400);
      });
      $siblings.removeClass('active');
      return $parent.addClass('active');
    });
    if (is_platform_page() && !!window.location.hash) {
      active_class = window.Foundation.libs.accordion.settings.active_class;
      $target = $("" + window.location.hash);
      $(".active").removeClass('active');
      if (window.location.hash.indexOf('pillar') > 0) {
        $('#by-portfolio').hide();
        $('#by-pillar').show();
        $('a[data-filter="#by-pillar"]').parent().addClass('active');
      } else {
        $('#by-pillar').hide();
        $('#by-portfolio').show();
        $('a[data-filter="#by-portfolio"]').parent().addClass('active');
      }
      $target.addClass('active');
      return $('html, body').animate({
        scrollTop: $target.offset().top - 150
      });
    }
  });

}).call(this);
